#!/bin/bash
############################
# shellrc
# Common configurations for bash and zsh
############################

# Alias definitions.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# local per-machine configurations
if [ -e ~/.bash_local ]; then
    . ~/.bash_local
fi

#stop ctrl+s ctrl+q behavior
stty -ixon

# set keyboard speed
xset r rate 180 70

# gnome specific keyboard speed and mouse focus
gsettings set org.gnome.desktop.peripherals.keyboard delay 170
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 10
gsettings set org.gnome.desktop.wm.preferences focus-mode sloppy

# prevent screen turning off too fast
gsettings set org.gnome.desktop.session idle-delay 300

# set GOPATH
export GOPATH="/home/janjitsu/.go"

# add go to path
export PATH="$PATH:$GOPATH/bin"

# python packages
export PATH="$HOME/.local/bin:$PATH"

# rbenv for ruby version management
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
export PATH="/home/janjitsu/.rbenv/shims:${PATH}"
export RBENV_SHELL=zsh
# source "$HOME/.rbenv/completions/rbenv.zsh"
command rbenv rehash 2>/dev/null
rbenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(rbenv "sh-$command" "$@")";;
  *)
    command rbenv "$command" "$@";;
  esac
}


# n for node version management
export N_PREFIX=$HOME/.n
export PATH=$N_PREFIX/bin:$PATH


# start with tmux
if [ "$TMUX" = "" ]; then
    tmux
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/janjitsu/Programs/google-cloud-sdk/path.zsh.inc' ]; then . '/home/janjitsu/Programs/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/janjitsu/Programs/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/janjitsu/Programs/google-cloud-sdk/completion.zsh.inc'; fi
