#!/bin/bash
############################
# shellrc
# Common configurations for bash and zsh
############################

# Alias definitions.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# local per-machine configurations
if [ -e ~/.bash_local ]; then
    . ~/.bash_local
fi

#stop ctrl+s ctrl+q behavior
stty -ixon

# set keyboard speed
xset r rate 180 70

# make second left click on K400 work for a left handed mouse setup
# xinput set-button-map `xinput list --id-only "pointer:Logitech K400 Plus"` 3 2 1
# K400 mouse click default
xinput set-button-map `xinput list --id-only "pointer:Logitech K400 Plus"` 1 2 3

# gnome specific keyboard speed and mouse focus
gsettings set org.gnome.desktop.peripherals.keyboard delay 170
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 10
gsettings set org.gnome.desktop.wm.preferences focus-mode sloppy

# prevent screen turning off too fast
gsettings set org.gnome.desktop.session idle-delay 300

# set GOPATH
export GOPATH="/home/janjitsu/.local/go"
export GOBIN="/home/janjitsu/.go/bin"

# add go to path
export PATH="$PATH:$GOBIN"

# python packages
export PATH="/home/janjitsu/.local/bin:$PATH"

# rbenv for ruby version management
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
export PATH="/home/janjitsu/.rbenv/shims:${PATH}"
export RBENV_SHELL=zsh
# source "$HOME/.rbenv/completions/rbenv.zsh"
command rbenv rehash 2>/dev/null
rbenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(rbenv "sh-$command" "$@")";;
  *)
    command rbenv "$command" "$@";;
  esac
}


# n for node version management
export N_PREFIX=/home/janjitsu/.n
export PATH=$N_PREFIX/bin:$PATH


# start with tmux
if [ "$TMUX" = "" ]; then
    tmux
fi

# start showing neofetch
if command -v neofetch 2>&1 >/dev/null; then
    neofetch
fi

# show neofetch

## @TODO MOVE THIS to zsh
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/janjitsu/Programs/google-cloud-sdk/path.zsh.inc' ]; then . '/home/janjitsu/Programs/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/janjitsu/Programs/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/janjitsu/Programs/google-cloud-sdk/completion.zsh.inc'; fi

# use fzf on zsh history (ctrl+R)
source <(fzf --zsh)

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory


# ANDROID SDK
export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
#export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export ANDROID_AVD_HOME=~/.android/avd
export ANDROID_SDK_ROOT=/mnt/old_ubuntu/@home/janjitsu/Android/SDK
export ANDROID_SDK_HOME=/mnt/old_ubuntu/@home/janjitsu/Android/SDK
export ANDROID_HOME=/mnt/old_ubuntu/@home/janjitsu/Android/SDK
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Calibre dark mode
export CALIBRE_USE_DARK_PALETTE=1

# cargo rust packages
export PATH=$PATH:/home/janjitsu/.cargo/bin
