[accessibility]
ui_scale = 2.5

[bar.default]
center = [ "workspaces", "spacer_1", "active_window" ]
concave_edge_corners = true
end = [ "media", "spacer_1", "tray", "notifications", "network", "volume", "session" ]
margin_edge = 0
margin_ends = 0
radius_bottom_left = 12
radius_bottom_right = 12
radius_top_left = 0
radius_top_right = 0
scale = 3.2500000409781933
start = [ "launcher", "clock", "spacer_1", "group:g1" ]
thickness = 120

    [[bar.default.capsule_group]]
    border = ""
    fill = "on_secondary"
    id = "g1"
    members = [ "temp", "sysmon_2", "sysmon_3" ]
    opacity = 1.0
    padding = 6.0

[control_center]
width = 750

[desktop_widgets]
enabled = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1920.0
    cy = 1978.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
enable_daemon = false
scale = 2.5

[osd]
scale = 2.5

[shell]
clipboard_history_max_entries = 2000
clipboard_image_action_command = "satty -f -"
launch_apps_as_systemd_services = true
polkit_agent = true
settings_show_advanced = true

    [shell.animation]
    enabled = false
    speed = 2.1000000312924385

    [shell.greeter_sync]
    auto_sync = true

    [shell.panel]
    open_near_click_control_center = true
    session_placement = "floating"
    session_position = "center"

    [shell.screenshot]
    copy_to_clipboard = false
    pipe_command = "satty -f -"
    pipe_to_command = true
    save_to_file = false

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[system.monitor]
enabled = false
gpu_poll_seconds = 2

[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-rainbow"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "kcolorscheme", "kitty", "qt", "alacritty" ]

[wallpaper]
enabled = false
transition = []

    [wallpaper.default]
    path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

    [wallpaper.last]
    path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

[widget.clock]
color = "secondary"
format = "{:%H:%M %A %m/%d/%y}"

[widget.launcher]
color = "secondary"

[widget.media]
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
color = "secondary"

[widget.notifications]
color = "secondary"

[widget.session]
color = "error"

[widget.spacer_1]
type = "spacer"

[widget.sysmon_3]
glyph = "cpu-2"
stat = "ram_used"
type = "sysmon"

[widget.tray]
capsule = true
capsule_fill = "on_secondary"

[widget.volume]
color = "secondary"

[widget.workspaces]
active_pill_size = 2.5
capsule = true
capsule_fill = "on_primary"
inactive_pill_size = 1.0
pill_scale = 0.80000000000000004
